### ISSUE TITLE
update kiss

### ISSUE THREAD

**Issue by kyx0r** [kiss-community/repo#22]
Need to update kiss to use git versions here:
https://github.com/kiss-community/repo-main/blob/master/core/kiss/sources

And maybe update the build also.
Not sure on the best way to handle stuffs like website and wiki but for kiss itself maybe just

git+https://github.com/kiss-community/kiss.git

be the most convenient ?

**Comment by kyx0r** [comment]
That will make kiss dependent on git though? But it already is so should not be a problem. Also I find this very cringe: https://github.com/kiss-community/repo-main/blob/master/core/kiss/build#L19

Why would you install something that then remove it?  Most simple solution is to move the uneeded files into a different folder and not copy that folder during install, as it stands now what it is doing now I call a hack.

**Comment by dilyn-corner** [comment]
`kiss` has been updated, sorry for the delay, was testing some stuff. The source has also been redirected to kiss-community/kiss. 

`kiss` has always been at least semi-dependent on `git`; much of the whole system is, in a way. But pointing the source to the git repo could theoretically be catastrophic :) 

AFAIK those are simply removed afterwords because of the way Dylan decided to distribute the site; it just downloads a specified commit, there's nothing separate happening. So if I decided to package the site and wiki in a different way, then there would be no need to do removals; but that seems like potentially extra effort. It might get changed.
