### ISSUE TITLE
latest rootfs is broken #2

### ISSUE THREAD

**Issue by ghost** [kiss-community/repo#70]
When I extract rootfs as root, I get https://0x0.st/oSiA.txt. The `--no-same-owner` flag helps.
Also, when I try to build the package, I get:
`fatal: unable to access 'https://github.com/vim/vim/': error setting certificate file: /etc/ssl/certs/ca-certificates.crt
`

**Comment by illiliti** [comment]
> When I extract rootfs as root, I get https://0x0.st/oSiA.txt.

I think it fails because some files are not owned by root. You can get a list of such files by running this command: `tar -tvf kiss-chroot-2022.6-2.tar.xz | grep -v 'root/root'`

> fatal: unable to access 'https://github.com/vim/vim/': error setting certificate file: /etc/ssl/certs/ca-certificates.crt

As discussed in IRC, the workaround is: `ln -s /etc/ssl/cert.pem /etc/ssl/certs/ca-certificates.crt`

Maybe curl should be configured to use /etc/ssl/cert.pem by default? Via `--with-ca-bundle=FILE` or something...

**Comment by ghost** [comment]
> I think it fails because some files are not owned by root. You can get a list of such files by running this command: `tar -tvf kiss-chroot-2022.6-2.tar.xz | grep -v 'root/root'`

Yes, there are files owned by a non-root user

**Comment by ioraff** [comment]
I think both of these issues should be fixed in the latest release.

**Comment by ghost** [comment]
> I think both of these issues should be fixed in the latest release.

I confirm. Thank you!
